<?php

namespace app\models\base;

use Yii;

/**
 * This is the generated model base class for table "contact_operator".
 * DO NOT EDIT THIS CLASS MANUALLY!
 *
 * @property int $id ID
 * @property string|null $street Street/Postbox
 * @property string|null $city City
 * @property string|null $postal_code Postal Code
 * @property string|null $state State
 * @property string|null $country Country
 * @property string|null $website Website
 * @property string|null $comment Additional Information
 * @property string|null $operator_name Name of Operator
 * @property string|null $contact_email Contact Email
 * @property string|null $contact_phone Contact Phone
 */
abstract class BaseContactOperator extends \app\models\core\Base
{
    /* [i.e columnName => [displayColumn, relationName],[..]] */
    const MANY_TO_MANY_COLUMNS = [];
    /* [[i.e columnName => displayColumn],[..]] */
    const ONE_TO_MANY_COLUMNS = [];

    const MODULE = 'Contact';
    const SHORT_NAME = 'Operator';

    const NAME_ATTRIBUTE = 'id';
    const PARENT_CLASSNAME = '';
    const ANCESTORS = [];
    const DEFAULT_VALUES = [];


    public static function getFormFilters() {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'contact_operator';
    }
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return array_merge(parent::rules(), [
            [['street', 'city', 'postal_code', 'state', 'country', 'website', 'comment', 'operator_name', 'contact_email', 'contact_phone'], 'string', 'max' => 255],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'street' => Yii::t('app', 'Street/Postbox'),
            'city' => Yii::t('app', 'City'),
            'postal_code' => Yii::t('app', 'Postal Code'),
            'state' => Yii::t('app', 'State'),
            'country' => Yii::t('app', 'Country'),
            'website' => Yii::t('app', 'Website'),
            'comment' => Yii::t('app', 'Additional Information'),
            'operator_name' => Yii::t('app', 'Name of Operator'),
            'contact_email' => Yii::t('app', 'Contact Email'),
            'contact_phone' => Yii::t('app', 'Contact Phone'),
        ];
    }




    public function fields()
    {
        $fields = [
        ];
        return array_merge(parent::fields(), $fields);
    }

    public function load($data, $formName = null)
    {
        return parent::load($data, $formName);
    }




    /**
    * {@inheritdoc}
    */
    public function beforeDelete()
    {
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }


}

