<?php

namespace app\models\base;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use \app\models\GeologyStructure;

/**
* This is the search base model class for model "GeologyStructure".
* DO NOT EDIT THIS FILE.
*/
abstract class BaseGeologyStructureSearch extends GeologyStructure
{
    use \app\models\core\SearchModelTrait;

    public $program_id;
    public $expedition_id;
    public $site_id;
    public $hole_id;
    public $core_id;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'section_id', 'top', 'extent', 'contact_type', 'fault_type', 'foliation_type', 'lineation_type', 'other', 'deformation_style', 'sedimentary_structures', 'comment_sedimentary_structures', 'comment', 'dipdirection', 'dip', 'curator', 'program_id', 'expedition_id', 'site_id', 'hole_id', 'core_id'],'safe'],
        ];
    }

    public function getExtraSortAttributes () {
        return [
        ];
    }

    protected function addQueryColumns($query) {
        $this->addQueryColumn($query, 'id', 'number');
        $this->addQueryColumn($query, 'section_id', 'number');
        $this->addQueryColumn($query, 'top', 'number');
        $this->addQueryColumn($query, 'extent', 'number');
        $this->addQueryColumn($query, 'contact_type', 'string');
        $this->addQueryColumn($query, 'fault_type', 'string');
        $this->addQueryColumn($query, 'foliation_type', 'string');
        $this->addQueryColumn($query, 'lineation_type', 'string');
        $this->addQueryColumn($query, 'other', 'string');
        $this->addQueryColumn($query, 'deformation_style', 'string');
        $this->addQueryColumn($query, 'sedimentary_structures', 'string');
        $this->addQueryColumn($query, 'comment_sedimentary_structures', 'string');
        $this->addQueryColumn($query, 'comment', 'string');
        $this->addQueryColumn($query, 'dipdirection', 'number');
        $this->addQueryColumn($query, 'dip', 'number');
        $this->addQueryColumn($query, 'curator', 'number');
    }

    protected function addQuerySearchAttributes($query) {
        $joins = [];
        $this->addQuerySearchAttribute($query, 'program_id', 'project_expedition', 'project_site.expedition_id', 'project_expedition.id', $joins);
        $this->addQuerySearchAttribute($query, 'expedition_id', 'project_site', 'project_hole.site_id', 'project_site.id', $joins);
        $this->addQuerySearchAttribute($query, 'site_id', 'project_hole', 'core_core.hole_id', 'project_hole.id', $joins);
        $this->addQuerySearchAttribute($query, 'hole_id', 'core_core', 'core_section.core_id', 'core_core.id', $joins);
        $this->addQuerySearchAttribute($query, 'core_id', 'core_section', 'geology_structure.section_id', 'core_section.id', $joins);
        $this->createSearchJoins($query, $joins);
    }

}