<?php

namespace app\models\base;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use \app\models\ArchiveFile;

/**
* This is the search base model class for model "ArchiveFile".
* DO NOT EDIT THIS FILE.
*/
abstract class BaseArchiveFileSearch extends ArchiveFile
{
    use \app\models\core\SearchModelTrait;


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'parent_combined_id', 'type', 'number', 'filename', 'original_filename', 'filesize', 'mime_type', 'checksum', 'upload_date', 'expedition_id', 'site_id', 'hole_id', 'core_id', 'section_id', 'section_split_id', 'sample_id', 'sample_request_id', 'remarks', 'metadata', 'analyst'],'safe'],
        ];
    }

    public function getExtraSortAttributes () {
        return [
        ];
    }

    protected function addQueryColumns($query) {
        $this->addQueryColumn($query, 'id', 'number');
        $this->addQueryColumn($query, 'parent_combined_id', 'string');
        $this->addQueryColumn($query, 'type', 'string');
        $this->addQueryColumn($query, 'number', 'number');
        $this->addQueryColumn($query, 'filename', 'string');
        $this->addQueryColumn($query, 'original_filename', 'string');
        $this->addQueryColumn($query, 'filesize', 'number');
        $this->addQueryColumn($query, 'mime_type', 'string');
        $this->addQueryColumn($query, 'checksum', 'string');
        $this->addQueryColumn($query, 'upload_date', 'datetime');
        $this->addQueryColumn($query, 'expedition_id', 'number');
        $this->addQueryColumn($query, 'site_id', 'number');
        $this->addQueryColumn($query, 'hole_id', 'number');
        $this->addQueryColumn($query, 'core_id', 'number');
        $this->addQueryColumn($query, 'section_id', 'number');
        $this->addQueryColumn($query, 'section_split_id', 'number');
        $this->addQueryColumn($query, 'sample_id', 'number');
        $this->addQueryColumn($query, 'request_id', '');
        $this->addQueryColumn($query, 'remarks', 'string');
        $this->addQueryColumn($query, 'metadata', 'string');
        $this->addQueryColumn($query, 'analyst', 'string');
    }

    protected function addQuerySearchAttributes($query) {
        $joins = [];
        $this->createSearchJoins($query, $joins);
    }

}