<?php

namespace app\models\base;

use Yii;

/**
 * This is the generated model base class for table "contact_organisation".
 * DO NOT EDIT THIS CLASS MANUALLY!
 *
 * @property int $id ID
 * @property string|null $organisation_name Name of Organisation 
 * @property string|null $department Department
 * @property string|null $street Street/Postbox
 * @property string|null $city City
 * @property string|null $postal_code Postal Code
 * @property string|null $state State
 * @property string|null $country Country
 * @property string|null $website Website
 * @property string|null $comment Additional Information
 * @property string|null $organisation_name_abbreviation Organisation Name Abbreviation
 */
abstract class BaseContactOrganisation extends \app\models\core\Base
{
    /* [i.e columnName => [displayColumn, relationName],[..]] */
    const MANY_TO_MANY_COLUMNS = [];
    /* [[i.e columnName => displayColumn],[..]] */
    const ONE_TO_MANY_COLUMNS = [];

    const MODULE = 'Contact';
    const SHORT_NAME = 'Organisation';

    const NAME_ATTRIBUTE = 'id';
    const PARENT_CLASSNAME = '';
    const ANCESTORS = [];
    const DEFAULT_VALUES = [];


    public static function getFormFilters() {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'contact_organisation';
    }
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return array_merge(parent::rules(), [
            [['organisation_name', 'department', 'street', 'city', 'postal_code', 'state', 'country', 'website', 'comment', 'organisation_name_abbreviation'], 'string', 'max' => 255],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'organisation_name' => Yii::t('app', 'Name of Organisation '),
            'department' => Yii::t('app', 'Department'),
            'street' => Yii::t('app', 'Street/Postbox'),
            'city' => Yii::t('app', 'City'),
            'postal_code' => Yii::t('app', 'Postal Code'),
            'state' => Yii::t('app', 'State'),
            'country' => Yii::t('app', 'Country'),
            'website' => Yii::t('app', 'Website'),
            'comment' => Yii::t('app', 'Additional Information'),
            'organisation_name_abbreviation' => Yii::t('app', 'Organisation Name Abbreviation'),
        ];
    }




    public function fields()
    {
        $fields = [
        ];
        return array_merge(parent::fields(), $fields);
    }

    public function load($data, $formName = null)
    {
        return parent::load($data, $formName);
    }




    /**
    * {@inheritdoc}
    */
    public function beforeDelete()
    {
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }


}

