<?php

namespace app\models\base;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use \app\models\ProjectExpedition;

/**
* This is the search base model class for model "ProjectExpedition".
* DO NOT EDIT THIS FILE.
*/
abstract class BaseProjectExpeditionSearch extends ProjectExpedition
{
    use \app\models\core\SearchModelTrait;


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'program_id', 'exp_acronym', 'expedition', 'exp_name', 'exp_name_alt', 'chief_scientists', 'contact', 'country', 'rock_classification', 'geological_age', 'funding_agency', 'objectives', 'keywords', 'comment', 'start_date', 'end_date'],'safe'],
        ];
    }

    public function getExtraSortAttributes () {
        return [
        ];
    }

    protected function addQueryColumns($query) {
        $this->addQueryColumn($query, 'id', 'number');
        $this->addQueryColumn($query, 'program_id', 'number');
        $this->addQueryColumn($query, 'expedition', 'string');
        $this->addQueryColumn($query, 'exp_name', 'string');
        $this->addQueryColumn($query, 'exp_name_alt', 'string');
        $this->addQueryColumn($query, 'exp_acronym', 'string');
        $this->addQueryColumn($query, 'chief_scientists', 'string');
        $this->addQueryColumn($query, 'contact', 'string');
        $this->addQueryColumn($query, 'start_date', 'string');
        $this->addQueryColumn($query, 'end_date', 'string');
        $this->addQueryColumn($query, 'keywords', 'string');
        $this->addQueryColumn($query, 'objectives', 'string');
        $this->addQueryColumn($query, 'rock_classification', 'string');
        $this->addQueryColumn($query, 'geological_age', 'string');
        $this->addQueryColumn($query, 'funding_agency', 'string');
        $this->addQueryColumn($query, 'comment', 'string');
        $this->addQueryColumn($query, 'country', 'string');
    }

    protected function addQuerySearchAttributes($query) {
        $joins = [];
        $this->createSearchJoins($query, $joins);
    }

}