<?php

namespace app\models\base;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use \app\models\CoreSection;

/**
* This is the search base model class for model "CoreSection".
* DO NOT EDIT THIS FILE.
*/
abstract class BaseCoreSectionSearch extends CoreSection
{
    use \app\models\core\SearchModelTrait;

    public $program_id;
    public $expedition_id;
    public $site_id;
    public $hole_id;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'core_id', 'section', 'combined_id', 'section_length', 'curated_length', 'core_catcher', 'section_condition', 'mcd_offset', 'curator', 'comment', 'comment_depth', 'program_id', 'expedition_id', 'site_id', 'hole_id'],'safe'],
        ];
    }

    public function getExtraSortAttributes () {
        return [
        ];
    }

    protected function addQueryColumns($query) {
        $this->addQueryColumn($query, 'id', 'number');
        $this->addQueryColumn($query, 'core_id', 'number');
        $this->addQueryColumn($query, 'section', 'number');
        $this->addQueryColumn($query, 'combined_id', 'string');
        $this->addQueryColumn($query, 'section_length', 'number');
        $this->addQueryColumn($query, 'curated_length', 'number');
        $this->addQueryColumn($query, 'core_catcher', 'boolean');
        $this->addQueryColumn($query, 'section_condition', 'string');
        $this->addQueryColumn($query, 'mcd_offset', 'number');
        $this->addQueryColumn($query, 'curator', 'string');
        $this->addQueryColumn($query, 'comment', 'string');
        $this->addQueryColumn($query, 'comment_depth', 'string');
    }

    protected function addQuerySearchAttributes($query) {
        $joins = [];
        $this->addQuerySearchAttribute($query, 'program_id', 'project_expedition', 'project_site.expedition_id', 'project_expedition.id', $joins);
        $this->addQuerySearchAttribute($query, 'expedition_id', 'project_site', 'project_hole.site_id', 'project_site.id', $joins);
        $this->addQuerySearchAttribute($query, 'site_id', 'project_hole', 'core_core.hole_id', 'project_hole.id', $joins);
        $this->addQuerySearchAttribute($query, 'hole_id', 'core_core', 'core_section.core_id', 'core_core.id', $joins);
        $this->createSearchJoins($query, $joins);
    }

}