<?php

namespace app\models\base;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use \app\models\CurationCorebox;

/**
* This is the search base model class for model "CurationCorebox".
* DO NOT EDIT THIS FILE.
*/
abstract class BaseCurationCoreboxSearch extends CurationCorebox
{
    use \app\models\core\SearchModelTrait;

    public $program_id;
    public $expedition_id;
    public $site_id;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'hole_id', 'corebox', 'corebox_combined_id', 'combined_id', 'comment', 'storage_id', 'program_id', 'expedition_id', 'site_id'],'safe'],
        ];
    }

    public function getExtraSortAttributes () {
        return [
        ];
    }

    protected function addQueryColumns($query) {
        $this->addQueryColumn($query, 'id', 'number');
        $this->addQueryColumn($query, 'hole_id', 'number');
        $this->addQueryColumn($query, 'corebox', 'string');
        $this->addQueryColumn($query, 'combined_id', 'string');
        $this->addQueryColumn($query, 'comment', 'string');
        $this->addQueryColumn($query, 'storage_id', 'number');
        $this->addQueryColumn($query, 'corebox_combined_id', 'string');
    }

    protected function addQuerySearchAttributes($query) {
        $joins = [];
        $this->addQuerySearchAttribute($query, 'program_id', 'project_expedition', 'project_site.expedition_id', 'project_expedition.id', $joins);
        $this->addQuerySearchAttribute($query, 'expedition_id', 'project_site', 'project_hole.site_id', 'project_site.id', $joins);
        $this->addQuerySearchAttribute($query, 'site_id', 'project_hole', 'curation_corebox.hole_id', 'project_hole.id', $joins);
        $this->createSearchJoins($query, $joins);
    }

}