<?php

namespace app\models\base;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use \app\models\ProjectSite;

/**
* This is the search base model class for model "ProjectSite".
* DO NOT EDIT THIS FILE.
*/
abstract class BaseProjectSiteSearch extends ProjectSite
{
    use \app\models\core\SearchModelTrait;

    public $program_id;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'expedition_id', 'combined_id', 'site', 'site_name', 'site_name_alt', 'type_drilling_location', 'description', 'city', 'county', 'state', 'country', 'comment', 'lithology', 'geological_age', 'program_id'],'safe'],
        ];
    }

    public function getExtraSortAttributes () {
        return [
        ];
    }

    protected function addQueryColumns($query) {
        $this->addQueryColumn($query, 'id', 'number');
        $this->addQueryColumn($query, 'expedition_id', 'number');
        $this->addQueryColumn($query, 'combined_id', 'string');
        $this->addQueryColumn($query, 'site', 'string');
        $this->addQueryColumn($query, 'site_name', 'string');
        $this->addQueryColumn($query, 'site_name_alt', 'string');
        $this->addQueryColumn($query, 'type_drilling_location', 'string');
        $this->addQueryColumn($query, 'description', 'string');
        $this->addQueryColumn($query, 'country', 'string');
        $this->addQueryColumn($query, 'state', 'string');
        $this->addQueryColumn($query, 'county', 'string');
        $this->addQueryColumn($query, 'city', 'string');
        $this->addQueryColumn($query, 'lithology', 'string');
        $this->addQueryColumn($query, 'geological_age', 'string');
        $this->addQueryColumn($query, 'comment', 'string');
    }

    protected function addQuerySearchAttributes($query) {
        $joins = [];
        $this->addQuerySearchAttribute($query, 'program_id', 'project_expedition', 'project_site.expedition_id', 'project_expedition.id', $joins);
        $this->createSearchJoins($query, $joins);
    }

}