<?php

namespace app\models\base;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use \app\models\CurationStorage;

/**
* This is the search base model class for model "CurationStorage".
* DO NOT EDIT THIS FILE.
*/
abstract class BaseCurationStorageSearch extends CurationStorage
{
    use \app\models\core\SearchModelTrait;


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'storage', 'combined_id', 'type', 'parent_id', 'exp_acronym', 'comment'],'safe'],
        ];
    }

    public function getExtraSortAttributes () {
        return [
        ];
    }

    protected function addQueryColumns($query) {
        $this->addQueryColumn($query, 'id', 'number');
        $this->addQueryColumn($query, 'storage', 'string');
        $this->addQueryColumn($query, 'combined_id', 'string');
        $this->addQueryColumn($query, 'type', 'string');
        $this->addQueryColumn($query, 'parent_id', 'number');
        $this->addQueryColumn($query, 'exp_acronym', 'string');
        $this->addQueryColumn($query, 'comment', 'string');
    }

    protected function addQuerySearchAttributes($query) {
        $joins = [];
        $this->createSearchJoins($query, $joins);
    }

}