<?php

namespace app\models\base;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use \app\models\ContactPerson;

/**
* This is the search base model class for model "ContactPerson".
* DO NOT EDIT THIS FILE.
*/
abstract class BaseContactPersonSearch extends ContactPerson
{
    use \app\models\core\SearchModelTrait;


    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'first_name', 'last_name', 'title', 'gender', 'orcid', 'phone', 'mobile', 'email', 'affiliation', 'comment', 'person_acronym', 'role'],'safe'],
        ];
    }

    public function getExtraSortAttributes () {
        return [
        ];
    }

    protected function addQueryColumns($query) {
        $this->addQueryColumn($query, 'id', 'number');
        $this->addQueryColumn($query, 'first_name', 'string');
        $this->addQueryColumn($query, 'last_name', 'string');
        $this->addQueryColumn($query, 'gender', 'string');
        $this->addQueryColumn($query, 'title', 'string');
        $this->addQueryColumn($query, 'orcid', 'string');
        $this->addQueryColumn($query, 'email', 'string');
        $this->addQueryColumn($query, 'phone', 'string');
        $this->addQueryColumn($query, 'mobile', 'string');
        $this->addQueryColumn($query, 'comment', 'string');
        $this->addQueryColumn($query, 'affiliation', 'string');
        $this->addQueryColumn($query, 'role', 'string');
        $this->addQueryColumn($query, 'person_acronym', 'string');
    }

    protected function addQuerySearchAttributes($query) {
        $joins = [];
        $this->createSearchJoins($query, $joins);
    }

}