<?php

namespace app\models\base;

use Yii;
use yii\base\Model;
use yii\data\ActiveDataProvider;
use \app\models\CoreCore;

/**
* This is the search base model class for model "CoreCore".
* DO NOT EDIT THIS FILE.
*/
abstract class BaseCoreCoreSearch extends CoreCore
{
    use \app\models\core\SearchModelTrait;

    public $program_id;
    public $expedition_id;
    public $site_id;

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'hole_id', 'core', 'combined_id', 'curator', 'core_ondeck', 'core_type', 'drillers_top_depth', 'drilled_length', 'core_recovery', 'core_loss_reason', 'continuity', 'section_count', 'core_diameter', 'core_oriented', 'rqd', 'igsn', 'fluid_type', 'bit_size', 'barrel_length', 'comment', 'comment_drilling', 'comment_depth', 'comment_identifier', 'program_id', 'expedition_id', 'site_id'],'safe'],
        ];
    }

    public function getExtraSortAttributes () {
        return [
        ];
    }

    protected function addQueryColumns($query) {
        $this->addQueryColumn($query, 'id', 'number');
        $this->addQueryColumn($query, 'hole_id', 'number');
        $this->addQueryColumn($query, 'combined_id', 'string');
        $this->addQueryColumn($query, 'core', 'number');
        $this->addQueryColumn($query, 'igsn', 'string');
        $this->addQueryColumn($query, 'core_ondeck', 'datetime');
        $this->addQueryColumn($query, 'drillers_top_depth', 'number');
        $this->addQueryColumn($query, 'drilled_length', 'number');
        $this->addQueryColumn($query, 'bit_size', 'string');
        $this->addQueryColumn($query, 'barrel_length', 'number');
        $this->addQueryColumn($query, 'fluid_type', 'string');
        $this->addQueryColumn($query, 'core_recovery', 'number');
        $this->addQueryColumn($query, 'core_loss_reason', 'string');
        $this->addQueryColumn($query, 'core_type', 'string');
        $this->addQueryColumn($query, 'core_oriented', 'boolean');
        $this->addQueryColumn($query, 'core_diameter', 'number');
        $this->addQueryColumn($query, 'continuity', 'string');
        $this->addQueryColumn($query, 'section_count', 'number');
        $this->addQueryColumn($query, 'rqd', 'string');
        $this->addQueryColumn($query, 'curator', 'string');
        $this->addQueryColumn($query, 'comment', 'string');
        $this->addQueryColumn($query, 'comment_identifier', 'string');
        $this->addQueryColumn($query, 'comment_depth', 'string');
        $this->addQueryColumn($query, 'comment_drilling', 'string');
        $this->addQueryColumn($query, 'site_id', '');
        $this->addQueryColumn($query, 'test123', '');
    }

    protected function addQuerySearchAttributes($query) {
        $joins = [];
        $this->addQuerySearchAttribute($query, 'program_id', 'project_expedition', 'project_site.expedition_id', 'project_expedition.id', $joins);
        $this->addQuerySearchAttribute($query, 'expedition_id', 'project_site', 'project_hole.site_id', 'project_site.id', $joins);
        $this->addQuerySearchAttribute($query, 'site_id', 'project_hole', 'core_core.hole_id', 'project_hole.id', $joins);
        $this->createSearchJoins($query, $joins);
    }

}