<?php

namespace app\models\base;

use Yii;

/**
 * This is the generated model base class for table "auxiliary_tables_survey_tools".
 * DO NOT EDIT THIS CLASS MANUALLY!
 *
 * @property int $id ID
 * @property string|null $method_short Method
 * @property string|null $tool_name Name of Tool
 * @property string|null $organisaton_name_abbreviation Abbreviation of Organisaton
 * @property string|null $comment Additional Information
 */
abstract class BaseAuxiliaryTablesSurveyTools extends \app\models\core\Base
{
    /* [i.e columnName => [displayColumn, relationName],[..]] */
    const MANY_TO_MANY_COLUMNS = [];
    /* [[i.e columnName => displayColumn],[..]] */
    const ONE_TO_MANY_COLUMNS = [];

    const MODULE = 'AuxiliaryTables';
    const SHORT_NAME = 'SurveyTools';

    const NAME_ATTRIBUTE = 'id';
    const PARENT_CLASSNAME = '';
    const ANCESTORS = [];
    const DEFAULT_VALUES = [];


    public static function getFormFilters() {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'auxiliary_tables_survey_tools';
    }
    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return array_merge(parent::rules(), [
            [['method_short', 'tool_name', 'organisaton_name_abbreviation', 'comment'], 'string', 'max' => 255],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'method_short' => Yii::t('app', 'Method'),
            'tool_name' => Yii::t('app', 'Name of Tool'),
            'organisaton_name_abbreviation' => Yii::t('app', 'Abbreviation of Organisaton'),
            'comment' => Yii::t('app', 'Additional Information'),
        ];
    }




    public function fields()
    {
        $fields = [
        ];
        return array_merge(parent::fields(), $fields);
    }

    public function load($data, $formName = null)
    {
        return parent::load($data, $formName);
    }




    /**
    * {@inheritdoc}
    */
    public function beforeDelete()
    {
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }


}

